name: Django CI/CD deploy to PythonAnywhere

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./pcstore/requirements.txt

    - name: Run tests
      run: |
        python ./pcstore/manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Install PythonAnywhere CLI and deploy
        run: |
          python -m pip install --upgrade pip
          pip install --user pythonanywhere
  
          export PATH=$HOME/.local/bin:$PATH
  
          echo "‚úÖ PATH: $PATH"
          echo "üìÇ List .local/bin:"
          ls -la $HOME/.local/bin
  
          echo "üîç Check pythonanywhere location:"
          which pythonanywhere || echo "‚ùå Not found"
          pythonanywhere --version || echo "‚ùå Cannot get version"
  
          echo "üöÄ Reloading app..."
          pythonanywhere api webapp reload \
            --username ${{ secrets.PA_USERNAME }} \
            --api_token ${{ secrets.PA_API_TOKEN }} \
            --domain_name ${{ secrets.PA_SITE_NAME }}
